### ISSUE TITLE
Turn rate of frigate too slow

### ISSUE THREAD

**Issue by vanosten** [l0k1/oprf_assets#11]
In fdm.nas, line 24:

var heading_ps = 0.1  # Change in heading per second at full rudder deflection

This is too slow. See e.g. http://shipcomrade.com/?p=1306 or https://www.reddit.com/r/WorldOfWarships/comments/ch405e/turning_radii_of_tier_7_destroyers_visualized/, https://en.wikipedia.org/wiki/Sachsen-class_frigate. The rate for a frigate should at least be 5.0 IMO - also to be able to navigate in tight areas. I.e. a 180 degree turn in 36 seconds.

**Comment by l0k1** [comment]
fixed, thanks!
