### ISSUE TITLE
sqlite error for GCI

### ISSUE THREAD

**Issue by vanosten** [l0k1/oprf_assets#12]
Using next on Linux - trying to run GCI as part of OPRF assets (actually admin)

   32.44 [INFO]:general    ======== ==========
   32.44 [INFO]:input      Reading materials from /home/vanosten/bin/flightgear/dnc-managed/install/flightgear/fgdata/Materials/regions/materials.xml
   34.64 [INFO]:systems    Reading systems from Path "/home/vanosten/bin/flightgear/dnc-managed/install/flightgear/fgdata/Aircraft/Generic/generic-systems.xml"
   34.64 [INFO]:cockpit    Initializing HUD Instrument
   34.64 [ALRT]:sound      No path in sim/sound/path
   34.64 [INFO]:general    Creating subsystems took:2200
   34.64 [INFO]:view       Splash screen progress binding-subsystems
   34.69 [ALRT]:navaid     NavCache contention on commit, will retry:1
   34.72 [ALRT]:navaid     NavCache contention on commit, will retry:2
   34.75 [ALRT]:navaid     NavCache contention on commit, will retry:3
   34.79 [ALRT]:navaid     NavCache contention on commit, will retry:4
   34.84 [ALRT]:navaid     NavCache contention on commit, will retry:5
   34.90 [ALRT]:navaid     NavCache contention on commit, will retry:6
   34.97 [ALRT]:navaid     NavCache contention on commit, will retry:7
   35.05 [ALRT]:navaid     NavCache contention on commit, will retry:8
   35.14 [ALRT]:navaid     NavCache contention on commit, will retry:9
   35.24 [ALRT]:navaid     NavCache contention on commit, will retry:10
   35.24 [ALRT]:navaid     Sqlite error:database is locked for  5 while running:
        COMMIT
   35.58 [ALRT]:navaid     Sqlite error:cannot start a transaction within a transaction (1) while running:

**Comment by l0k1** [comment]
That doesnt look like an error with the GCI, it looks like FlightGear is erroring out while trying to pull info from the navaid database.
