### ISSUE TITLE
Incorrect case for texture files

### ISSUE THREAD

**Issue by colingeniet** [l0k1/oprf_assets#13]
There are some missing textures errors in the new models due to incorrect case:
- In `depot/Models/HardShelter`, 3 texture files `Hardshelter...` included as `HardShelter...` in the `.ac`
- In `depot/Models/MilCheckpoint`, 6 texture files with lower case hexadecimal names (e.g. `163bd35f.jpg`), included as upper case in the `.ac`

**Comment by NikolaiVChr** [comment]
fixed
