### ISSUE TITLE
PAC-2 should not alert RWR

### ISSUE THREAD

**Issue by BobDotCom** [l0k1/oprf_assets#24]
Patriot uses TVM, so it shouldn't alert enemy RWR. Also I believe the ground radar should continue painting the target until the missile is in the terminal phase to provide guidance.

**Comment by NikolaiVChr** [comment]
Yes, we are aware of TVM. Will get around to make it at some point soon_tm..

**Comment by NikolaiVChr** [comment]
Soon is now, fixed I hope.
